BlogApp/urls.py
import debug_toolbar

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('accounts/', include('allauth.urls')),
                  path('', include('core.urls')),
                  path('summernote/', include('django_summernote.urls')),
                  path('__debug__/', include(debug_toolbar.urls)),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from .views import HomeView, DetailView, UpvoteView, CategoryView, TagView, AddSubscriberView, SearchView, ContactUsView

app_name = "core"

urlpatterns = [
    path('', HomeView, name='HomeView'),
    path('blog/<slug:slug>/', DetailView, name='DetailView'),
    path('upvote/<slug:slug>/', UpvoteView, name='UpvoteView'),
    path('category/<slug:slug>/', CategoryView, name='CategoryView'),
    path('tags/<slug:slug>/', TagView, name='TagView'),
    path('subscribe/', AddSubscriberView, name='AddSubscriberView'),
    path('search/', SearchView, name='SearchView'),
    path('contact-us/', ContactUsView, name='ContactUsView'),


]

core/models.py
from django.db import models
from accounts.models import User
from django.utils.text import slugify
from taggit.managers import TaggableManager
from django.urls import reverse
from django.utils import timezone


# Create your models here.

class Categories(models.Model):
    category_name = models.CharField(max_length=255)

    def __str__(self):
        return self.category_name


class BlogPost(models.Model):
    title = models.CharField(max_length=450)
    slug = models.SlugField(null=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    tags = TaggableManager()
    img = models.ImageField(upload_to='blog', null=True)
    blog = models.TextField(max_length=50000)
    post_date = models.DateTimeField(auto_now=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    category = models.ForeignKey(Categories, blank=True, on_delete=models.PROTECT, related_name='category_set')
    upvote = models.ManyToManyField(User, related_name='blog_liked', blank=True)
    Approved = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(BlogPost, self).save(*args, **kwargs)

    def total_upvote(self):
        return self.upvote.count()

    def total_upvote(self):
        return self.upvote.count()

    def get_absolute_url(self):
        return reverse('core:DetailView', kwargs={'slug': self.slug})

    def __str__(self):
        return self.title + " | " + self.author.first_name + " " + self.author.last_name


class Comment(models.Model):
    post = models.ForeignKey(BlogPost, on_delete=models.CASCADE, related_name='comments')
    sender = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    sender_email = models.EmailField(null=True, blank=True)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.message


class Subscriber(models.Model):
    email = models.EmailField()
    added_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.email


class Contact(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    message = models.TextField()

    def __str__(self):
        return self.email + " | " + self.message

core/views.py
import datetime
from random import randint

from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, redirect, get_object_or_404
from .models import BlogPost, Comment, Categories, Subscriber, Contact
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from taggit.models import Tag


def PopularPosts():
    week_ago = datetime.date.today() - datetime.timedelta(days=7)
    trends = BlogPost.objects.filter(post_date__gte=week_ago).order_by('-id')[:6]
    if len(trends) < 6:
        month_ago = datetime.date.today() - datetime.timedelta(days=30)
        trends = BlogPost.objects.filter(post_date__gte=month_ago).order_by('-id')[:6]
    return trends


def HomeView(request):
    query_set = BlogPost.objects.all().order_by('-id')
    trends = PopularPosts()
    categories_qs = Categories.objects.all()
    paginator = Paginator(query_set, 4)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)

    context = {
        'count': paginator.count,
        'page': page,
        'category': categories_qs,
        'tags': Tag.objects.all(),
        'trends': trends,
    }
    return render(request, 'core/home.html', context)


def DetailView(request, slug):
    query_set = BlogPost.objects.get(slug=slug)
    related_qs = BlogPost.objects.filter(tags__in=query_set.tags.all()).exclude(slug=slug)[:3]
    trends = PopularPosts()
    comments = query_set.comments.all().order_by('-id')

    if request.method == 'POST':
        message = request.POST.get('message')
        email = request.POST.get('email')
        if message is not None:
            print("check")
            if request.user.is_authenticated:
                obj = Comment.objects.create(post=query_set, sender=request.user, message=message)
                print(obj.sender, "--1--")
                return JsonResponse(
                    {'commenter': obj.sender.first_name + " " + obj.sender.first_name, 'created_at': obj.created_at,
                     'msg': obj.message})
            else:
                obj = Comment.objects.create(post=query_set, sender_email=email, message=message)
                print(obj, "--2--")
                return JsonResponse({'commenter': "Unknown", 'created_at': obj.created_at, 'msg': obj.message})

    context = {
        'object': query_set,
        'related_posts': related_qs,
        'comments': comments,
        'trends': trends,
    }
    return render(request, 'core/detail.html', context)


def UpvoteView(request, slug):
    query_set = BlogPost.objects.get(slug=slug)
    print(query_set, "qs--->1")
    query_set.upvote.add(request.user)
    query_set.save()
    print(query_set, "qs--->1")

    return redirect('core:DetailView', slug=slug)


def CategoryView(request, slug):
    query_set = BlogPost.objects.select_related('category').filter(category__category_name=slug)
    paginator = Paginator(query_set, 6)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    trends = PopularPosts()

    context = {
        'count': paginator.count,
        'page': page,
        'slug': slug,
        'trends': trends,
    }
    return render(request, 'core/category_and_tags.html', context)


def TagView(request, slug):
    query_set = BlogPost.objects.filter(tags__slug=slug)
    print(query_set, "tags--->")
    paginator = Paginator(query_set, 6)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    trends = PopularPosts()

    context = {
        'count': paginator.count,
        'page': page,
        'slug': slug,
        'trends': trends,
    }
    return render(request, 'core/category_and_tags.html', context)


def AddSubscriberView(request):
    if request.method == "POST":
        email = request.POST.get('email')
        if Subscriber.objects.filter(email=email).exists():
            return JsonResponse({'added': "False", })
        else:
            Subscriber.objects.create(email=email)
            return JsonResponse({'added': "True", })


def SearchView(request):
    trends = PopularPosts()
    if request.method == 'POST':
        query = request.POST.get('search_form')
    if len(query) > 80:
        all_posts = BlogPost.objects.none()
    elif len(query) <= 3:
        all_posts = BlogPost.objects.none()
    else:
        all_posts_title = BlogPost.objects.filter(title__icontains=query)
        all_posts_blog = BlogPost.objects.filter(blog__icontains=query)
        all_posts = all_posts_blog.union(all_posts_title)
    context = {
        'allPosts': all_posts,
        'query': query,
        'trends': trends,
    }
    return render(request, 'core/search.html', context)


def ContactUsView(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        email = request.POST.get('email')
        message = request.POST.get('msg')
        Contact.objects.create(name=name, email=email, message=message)
        messages.info(request,
                      'We appreciate you for contacting us. One of our colleagues will get back in touch with you soon!Have a great day!')
    trends = PopularPosts()
    context = {
        'trends': trends,
    }
    return render(request, 'core/contact_us.html', context)

templates/core/category_and_tags.html
{% extends 'base.html' %}


{% block content %}
    <!--blog-psots-->
    <section id="posts">
        <div class="container">
            <div class="category_heading text-center">
                {% if page.object_list|length == 0 %}
                    <h1>No Blogs Found Related to <em>{{ slug }}</em></h1>

                {% else %}
                    <h1>Blogs Related to <em>{{ slug }}</em></h1>
                {% endif %}
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="two-col-sidebar">
                        {% for object in page.object_list %}
                            <article class="standard-post-format grid-box">
                                <div class="post-featured-image">
                                    <a href="{{ object.get_absolute_url }}"><img style="width: 100%; height: 276px" src="{{ object.img.url }}"
                                                     alt="image"></a>
                                </div>

                                <div class="the-post">
                                    <div class="post-title">
                                        {#                                        <h2><a href="#">Inside The Garden & <em>Blooming Flowers</em></a></h2>#}
                                        <h2><a href="{{ object.get_absolute_url }}">{{ object.title }}</a></h2>
                                    </div>
                                    <div class="post-meta-elements">
                                        <div class="meta-post-author">
                                            <i class="fa fa-user"></i><a
                                                href="#">{{ object.author.first_name }} {{ object.author.last_name }}</a>
                                        </div>

                                        <div id="tags" class="meta-post-cat">

                                            {% for tag in object.tags.all %}
                                                {% if forloop.counter == 1 %}
                                                    <i class="fa fa-tags"></i>
                                                {% endif %}
                                                <a href="#">{{ tag }}</a>,
                                            {% endfor %}
                                        </div>
                                        <div class="meta-post-date">
                                            <i class="fa fa-clock-o"></i>{{ object.post_date }}
                                        </div>
                                        <div class="meta-post-commetns">
                                            <i class="fa fa-arrow-up"></i><a href="#">{{ object.total_upvote }}</a>
                                        </div>
                                    </div>
                                    <div class="post_content">
                                        {{ object.blog|safe|truncatewords_html:40 }}
                                        <div class="readmore">
                                            <a href="{{ object.get_absolute_url }}" class="btn">Continue Reading..</a>
                                        </div>
                                    </div>
                                </div>
                            </article>
                        {% endfor %}


                    </div>
{% if page|length > 0 %}
                    <div class="pagination">
                        <ul>
                            {% if page.has_previous %}
                                <li><a href="{% url 'core:CategoryView' slug %}?page={{ page.previous_page_number }}"
                                       class="nav-prev">Prev</a></li>
                            {% endif %}
                            <li>
                                <span class="current">{{ page.number }}</span>
                            </li>
                            {% if page.has_next %}
                                <li><a href="{% url 'core:CategoryView' slug %}?page={{ page.next_page_number }}"
                                       class="nav-prev">Next</a></li>
                            {% endif %}

                        </ul>
                    </div>
{% endif %}

                </div>
            </div>
        </div>
    </section>
    <!--/blog-posts-->



{% endblock %}

templates/core/contact_us.html
{% extends 'base.html' %}


{% block content %}
    <section class="page_heading">
        <div class="container">
            <div class="text-center">
                <h1>Share Your <em>Story</em></h1>
                {#                <p>Lorem ipsum dolor sit amet, wisi paulo ut his, sumo mucius</p>#}
            </div>
        </div>
    </section>

    <!--contact-us-->
    <section id="contact_us" class="padding_none">
        <div class="container">
            <div class="padding_4x4_40 white_bg">
                <div class="row">
                    <div class="col-md-3"></div>
                    <div class="col-md-6">
                        <h3>Ask A <em>Question ?</em></h3>
                        <p>There are many variations of passages of Lorem Ipsum available</p>
                        <div class="space-30"></div>
                        <div class="contact_form">
                            {% for message in messages %}
                                {% if 'info' in message.tags %}
                                    <div class="success-message message">
                                        <div class="alert alert-info">
                                            <strong>{{ message }}</strong>
                                            <a style="margin-left: 5rem" href="#" class="del-msg">&times;</a>
                                        </div>
                                    </div>

                                {% endif %}
                            {% endfor %}
                            <form method="post">
                                {% csrf_token %}

                                <div class="form-group">
                                    <input name="name" id="id_name" type="text" placeholder="Name">
                                </div>
                                <div class="form-group">
                                    <input name="email" id="id_email" type="email" placeholder="Email Address">
                                </div>
                                <div class="form-group">
                                    <textarea name="msg" cols="id_msg" rows="" placeholder="Message"></textarea>
                                </div>
                                <div class="form-group">
                                    <input name="" type="submit" class="btn active_btn">
                                </div>
                            </form>
                        </div>
                    </div>
                    <div class="col-md-3"></div>

                </div>
            </div>
            <div class="space-60"></div>
        </div>
    </section>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
            integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script>

        $(document).ready(function () {
            // messages timeout for 10 sec
            //     setTimeout(function () {
            //       $('.message').fadeOut('slow');
            //  }, 10000);

            // delete message
            $('.del-msg').on('click', function () {
                $('.del-msg').parent().attr('style', 'display:none;');
            })
        });
    </script>
{% endblock %}

templates/core/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <!--post-slider-->
    <section id="myCarousel" class="carousel slide post-slider">
        <div class="container">
            <div class="carousel-inner">
                {% for object in page.object_list %}
                {% if forloop.counter == 1 %}
                <div class="item active">
                    <div class="post-slider-image"><img alt="car1" src="{{ object.img.url }}"></div>
                    <div class="post-slider-text">
                        <div class="post-slider-title">
                            <h2><a href="{{ object.get_absolute_url }}">{{ object.title }}</a></h2>
                        </div>
                        <div class="post-meta-elements">
                            <div class="meta-post-author">
                                <i class="fa fa-user"></i><a href="#">By:{{ object.author.first_name }} {{ object.author.last_name }}</a>
                            </div>
                            <div class="meta-post-date">
                                <i class="fa fa-clock-o"></i>{{ object.post_date }}
                            </div>
                        </div>
                        <div class="post-slider-content">
                            {{ object.blog|safe|truncatewords_html:20 }}
                        </div>
                    </div>
                </div>
                {% else %}
                <div class="item">
                    <div class="post-slider-image"><img alt="car1" src="{{ object.img.url }}">
                    </div>
                    <div class="post-slider-text">
                        <div class="post-slider-title">
                            <h2><a href="{{ object.get_absolute_url }}">{{ object.title }}</a></h2>
                        </div>
                        <div class="post-meta-elements">
                            <div class="meta-post-author">
                                <i class="fa fa-user"></i><a href="#">By:{{ object.author.first_name }} {{ object.author.last_name }}</a>
                            </div>
                          
                            <div class="meta-post-date">
                                <i class="fa fa-clock-o"></i>{{ object.post_date }}
                            </div>
                        </div>
                        <div class="post-slider-content">
                            {{ object.blog|safe|truncatewords_html:20 }}
                        </div>
                    </div>
                </div> 
                {% endif %}
                {% endfor %}
            </div>
            <a class="left carousel-control" href="#myCarousel" data-slide="prev"><span
                    class="glyphicon glyphicon-chevron-left"></span></a>
            <a class="right carousel-control" href="#myCarousel" data-slide="next"><span
                    class="glyphicon glyphicon-chevron-right"></span></a>
        </div>
    </section>
    <!--post-slider-end-->

    <!--blog-psots-->
    <section id="posts">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <div class="two-col-sidebar">
                        {% for object in page.object_list %}
                            <article class="standard-post-format grid-box">
                                <div class="post-featured-image">
                                    <a href="{{ object.get_absolute_url }}"><img style="width: 364px; height: 182px" src="{{ object.img.url }}"
                                                     alt="image"></a>
                                </div>

                                <div class="the-post">
                                    <div class="post-title">
                                        <!-- {#                                        <h2><a href="#">Inside The Garden & <em>Blooming Flowers</em></a></h2>#} -->
                                        <h2><a href="{{ object.get_absolute_url }}">{{ object.title }}</a></h2>
                                    </div>
                                    <div class="post-meta-elements">
                                        <div class="meta-post-author">
                                            <i class="fa fa-user"></i><a
                                                href="#">{{ object.author.first_name }} {{ object.author.last_name }}</a>
                                        </div>

                                        <div id="tags" class="meta-post-cat">

                                            {% for tag in object.tags.all %}
                                                {% if forloop.counter == 1 %}
                                                    <i class="fa fa-tags"></i>
                                                {% endif %}
                                                <a href="#">{{ tag }}</a>,
                                            {% endfor %}
                                        </div>
                                        <div class="meta-post-date">
                                            <i class="fa fa-clock-o"></i>{{ object.post_date }}
                                        </div>
                                        <div class="meta-post-commetns">
                                            <i class="fa fa-arrow-up"></i><a href="#">{{ object.total_upvote }}</a>
                                        </div>
                                    </div>
                                    <div class="post_content">
                                        {{ object.blog|safe|truncatewords_html:40 }}
                                        <div class="readmore">
                                            <a href="{{ object.get_absolute_url }}" class="btn">Continue Reading..</a>
                                        </div>
                                    </div>
                                </div>
                            </article>
                        {% endfor %}

                    </div>
                    <div class="pagination">
                        <ul>
                            {% if page.has_previous %}
                                <li><a href="{% url 'core:HomeView' %}?page={{ page.previous_page_number }}"
                                       class="nav-prev">Prev</a></li>
                            {% endif %}
                            <li>
                                <span class="current">{{ page.number }}</span>
                            </li>
                            {% if page.has_next %}
                                <li><a href="{% url 'core:HomeView' %}?page={{ page.next_page_number }}"
                                       class="nav-prev">Next</a></li>
                            {% endif %}

                        </ul>
                    </div>


                </div>

                <!-----sidebar----->

                <aside class="col-md-4">
                    <div class="sidebar">

                       

                        <div class="sidebar_widget grid-box widgetbox">
                            <h6 class="sidebar-title"><span>Categories</span></h6>
                            <div class="psot_categories">
                                {% if category|length >= 5 %}
                                    <ul style="width: 100%; height: 250px; overflow: auto">
                                        {% for category in category %}
                                            <li><a href="{% url 'core:CategoryView' category.category_name %}">{{ category.category_name }}</a></li>
                                        {% endfor %}

                                    </ul>
                                {% else %}
                                    <ul>
                                        {% for category in category %}
                                            <li><a href="{% url 'core:CategoryView' category.category_name %}">{{ category.category_name }}</a></li>
                                        {% endfor %}

                                    </ul>
                                {% endif %}
                            </div>
                        </div>

                        <div class="sidebar_widget grid-box widgetbox">
                            <h6 class="sidebar-title"><span>Tags</span></h6>
                            <div class="post_tags">
                                {% for tags in tags %}
                                <a href="{% url 'core:TagView' tags.slug %}">{{ tags.name }}</a>
                                {% endfor %}
                            </div>
                        </div>

                    </div>
                </aside>
                <!-----/sidebar----->
            </div>
        </div>
    </section>
    <!--/blog-posts-->


{% endblock %}

templates/core/search.html
{% extends 'base.html' %}


{% block content %}
    <!--blog-psots-->
    <section id="posts">
        <div class="container my-3">
            <h2>Search results : </h2>
            {% if allPosts|length < 1 %}
                <p>No search results</p>
                Your search query : <b>{{ query }}</b> did not match any documents. <br>
                <h4 style="margin-top: 2%">Suggestions:</h4>
                <ul>
                    <li>Make sure that all words are spelled correctly.</li>
                    <li>Try more general keywords.</li>
                    <li> Try fewer keywords.</li>
                    <li> Try different keywords.</li>
                    </li>
                </ul>


            {% endif %}
        </div>
        <div class="container">
            {#                <div class="category_heading text-center">#}
            {#                    {% if page.object_list|length == 0 %}#}
            {#                        <h1>No Blogs Found Related to <em>{{ slug }}</em></h1>#}
            {##}
            {#                    {% else %}#}
            {#                        <h1>Blogs Related to <em>{{ slug }}</em></h1>#}
            {#                    {% endif %}#}
            {#                </div>#}
            <div class="row">
                <div class="col-md-12">
                    <div class="two-col-sidebar">
                        {% for object in allPosts %}
                            <article class="standard-post-format grid-box">
                                <div class="post-featured-image">
                                    <a href="#"><img style="width: 100%; height: 276px" src="{{ object.img.url }}"
                                                     alt="image"></a>
                                </div>

                                <div class="the-post">
                                    <div class="post-title">
                                        {#                                        <h2><a href="#">Inside The Garden & <em>Blooming Flowers</em></a></h2>#}
                                        <h2><a href="#">{{ object.title }}</a></h2>
                                    </div>
                                    <div class="post-meta-elements">
                                        <div class="meta-post-author">
                                            <i class="fa fa-user"></i><a
                                                href="#">{{ object.author.first_name }} {{ object.author.last_name }}</a>
                                        </div>

                                        <div id="tags" class="meta-post-cat">

                                            {% for tag in object.tags.all %}
                                                {% if forloop.counter == 1 %}
                                                    <i class="fa fa-tags"></i>
                                                {% endif %}
                                                <a href="#">{{ tag }}</a>,
                                            {% endfor %}
                                        </div>
                                        <div class="meta-post-date">
                                            <i class="fa fa-clock-o"></i>{{ object.post_date }}
                                        </div>
                                        <div class="meta-post-commetns">
                                            <i class="fa fa-arrow-up"></i><a href="#">{{ object.total_upvote }}</a>
                                        </div>
                                    </div>
                                    <div class="post_content">
                                        {{ object.blog|safe|truncatewords_html:40 }}
                                        <div class="readmore">
                                            <a href="{{ object.get_absolute_url }}" class="btn">Continue
                                                Reading..</a>
                                        </div>
                                    </div>
                                </div>
                            </article>
                        {% endfor %}


                    </div>

                </div>
            </div>
        </div>
    </section>
    <!--/blog-posts-->



{% endblock %}