BlogApp/urls.py
import debug_toolbar

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('accounts/', include('allauth.urls')),
                  path('', include('core.urls')),
                  path('summernote/', include('django_summernote.urls')),
                  path('__debug__/', include(debug_toolbar.urls)),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from .views import HomeView, DetailView, UpvoteView, CategoryView, TagView, AddSubscriberView, SearchView, ContactUsView

app_name = "core"

urlpatterns = [
    path('', HomeView, name='HomeView'),
    path('blog/<slug:slug>/', DetailView, name='DetailView'),
    path('upvote/<slug:slug>/', UpvoteView, name='UpvoteView'),
    path('category/<slug:slug>/', CategoryView, name='CategoryView'),
    path('tags/<slug:slug>/', TagView, name='TagView'),
    path('subscribe/', AddSubscriberView, name='AddSubscriberView'),
    path('search/', SearchView, name='SearchView'),
    path('contact-us/', ContactUsView, name='ContactUsView'),


]

core/models.py
from django.db import models
from accounts.models import User
from django.utils.text import slugify
from taggit.managers import TaggableManager
from django.urls import reverse
from django.utils import timezone


# Create your models here.

class Categories(models.Model):
    category_name = models.CharField(max_length=255)

    def __str__(self):
        return self.category_name


class BlogPost(models.Model):
    title = models.CharField(max_length=450)
    slug = models.SlugField(null=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    tags = TaggableManager()
    img = models.ImageField(upload_to='blog', null=True)
    blog = models.TextField(max_length=50000)
    post_date = models.DateTimeField(auto_now=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    category = models.ForeignKey(Categories, blank=True, on_delete=models.PROTECT, related_name='category_set')
    upvote = models.ManyToManyField(User, related_name='blog_liked', blank=True)
    Approved = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(BlogPost, self).save(*args, **kwargs)

    def total_upvote(self):
        return self.upvote.count()

    def total_upvote(self):
        return self.upvote.count()

    def get_absolute_url(self):
        return reverse('core:DetailView', kwargs={'slug': self.slug})

    def __str__(self):
        return self.title + " | " + self.author.first_name + " " + self.author.last_name


class Comment(models.Model):
    post = models.ForeignKey(BlogPost, on_delete=models.CASCADE, related_name='comments')
    sender = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    sender_email = models.EmailField(null=True, blank=True)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.message


class Subscriber(models.Model):
    email = models.EmailField()
    added_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.email


class Contact(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    message = models.TextField()

    def __str__(self):
        return self.email + " | " + self.message

templates/auth_base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Blog Post</title>

    <!-- Bootstrap -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- custome-css -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css" media="screen">
    <!-- font awesome for icons -->
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
    <!-- google font -->
    <link href="{% static 'fonts/css8773.css?family=Merriweather:300,400,700' %}" rel='stylesheet' type='text/css'>
    <link href="{% static 'fonts/cssda6f.css?family=Open+Sans:400,600,700' %}" rel='stylesheet' type='text/css'>
    <!-- Fav and touch icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144"
          href="{% static 'images/favicon-icon/apple-touch-icon-144-precomposed.png' %}">
    <link rel="apple-touch-icon-precomposed" sizes="114x114"
          href="{% static 'images/favicon-icon/apple-touch-icon-114-precomposed.png' %}">
    <link rel="apple-touch-icon-precomposed" sizes="72x72"
          href="{% static 'images/favicon-icon/apple-touch-icon-72-precomposed.png' %}">
    <link rel="apple-touch-icon-precomposed"
          href="{% static 'images/favicon-icon/apple-touch-icon-57-precomposed.png' %}">
    <link rel="shortcut icon" href="{% static 'images/favicon-icon/favicon.png' %}">


</head>
<body>

<!--navigation-->
<header class="navbar navbar-inverse">
    <div class="container">
        <div class="row">
            <div class="col-md-2">
                <div class="logo">
                    <a href="index-2.html"><img src="{% static 'images/logo.png' %}" alt="logo-image"></a>
                </div>
            </div>

            <div class="col-md-7">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                            data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav text-right">
                        <li class="dropdown">
                            <a href="{% url 'core:HomeView' %}">Home</a>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Categories <b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href="{% url 'core:CategoryView' 'Entertainment' %}">Entertainment</a></li>
                                <li><a href="{% url 'core:CategoryView' 'Development' %}">Development</a></li>
                                <li><a href="{% url 'core:CategoryView' 'Business' %}">Business</a></li>
                                <li><a href="{% url 'core:CategoryView' 'Lifestyle' %}">Lifestyle</a></li>
                            </ul>
                        </li>
                        <li><a href="{% url 'core:ContactUsView' %}">Contact-Us</a></li>
                        <li><a href="{% url 'account_signup' %}">Write Blog for Us</a></li>
                        {% if request.user.is_authenticated %}
                            <li><a href="{% url 'account_logout' %}" style="background-color: transparent; !important;"
                                   class="active_btn">Logout</a></li>
                        {% else %}
                            <li><a href="{% url 'account_login' %}">Login</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>

            <div class="col-md-3">
                <div class="search">
                    <div class="search_button"><i class="fa fa-search"></i> <i class="fa fa-close"></i></div>
                    <form method="post" action="{% url 'core:SearchView' %}" role="form" id="search_form">
                        {% csrf_token %}
                        <div class="form-group has-feedback">
                            <input type="text" placeholder="Search.." name="search_form" id="id_search"
                                   class="form-control input-sm">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!--/.nav-collapse -->
</header>
<!--navigation end-->

<section class="page_heading">
    <div class="container">
        <div class="text-center">
            <h1>Start Journey With Us</h1>
            <!-- <p>Lorem ipsum dolor sit amet, wisi paulo ut his, sumo mucius</p> -->
        </div>
    </div>
</section>


<!--pricing-->
<section id="pricing" class="padding_none">
    <div class="container">
        <div class="row">
            <div class="col-md-6">

                <img src="{% static 'images/logo.png' %}">
                <p style="width: initial;">A company profile is a written introduction to a company that tells the
                    reader about its activities, mission, goals and strengths. Often, a company profile includes the
                    story of the company's founding and describes its products or services. In smaller businesses,
                    the company owner may write a company profile. However, larger companies can assign an employee
                    to this task. Company profiles can fulfill the following purposes:

                    Investment plans: Company profiles can give potential investors the information they need to
                    decide whether to provide funding for a company.
                    Company websites and social media: You can use a company profile to inform website and social
                    media users about your company's mission, values and origin.
                    There is no set length for company profiles. Some profiles are as short as two pages while
                    others span 10 or more. This length can depend on a number of factors, including the audience
                    for the company profile, the company's age and its size.

                </p>
            </div>
            {% block content %}


            {% endblock %}
        </div>
        <div class="space-80 margin-btm-20"></div>
    </div>
</section>
<!--/pricing-->

<!-----footer----->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-5">
                <div class="footer_logo">
                    <a href="index-2.html"><img src="{% static 'images/logo.png' %}" alt="logo-image"></a>
                </div>
                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the
                    industry's standard dummy text ever since the 1500s, when an unknown printer took a galley.</p>
                <div class="newslatter">
                    <h4>Subscribe <em>Newsletter</em></h4>
                    <p>Get my latest adventures and updates delivered straight to your inbox. </p>
                    <div class="row">
                        <form method="post" id="subscribeform">
                            {% csrf_token %}
                            <div class="form-group">
                                <div class="col-md-7 col-sm-8">
                                    <input name="email" id="id_email" type="email" placeholder="Enter your email here"
                                           required>
                                </div>
                                <div class="col-md-5 col-sm-4">
                                    <input name="" type="submit" value="Subscribe" class="btn active_btn">
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>

            <div class="col-md-7">
                <div class="instagram-feed text-center">
                    <a href="#" class="btn instagram_btn white-btn"><i class="fa fa-instagram"></i> Join Instagram</a>
                    <ul>
                        <li><a href="#"><img src="{% static 'images/instagram-feed-img1.jpg' %}"
                                             alt="instagram-feed"></a></li>

                        <li><a href="#"><img src="{% static 'images/instagram-feed-img2.jpg' %}"
                                             alt="instagram-feed"></a></li>
                        <li><a href="#"><img src="{% static 'images/instagram-feed-img3.jpg' %}"
                                             alt="instagram-feed"></a></li>
                        <li><a href="#"><img src="{% static 'images/instagram-feed-img4.jpg' %}"
                                             alt="instagram-feed"></a></li>
                        <li><a href="#"><img src="{% static 'images/instagram-feed-img5.jpg' %}"
                                             alt="instagram-feed"></a></li>
                        <li><a href="#"><img src="{% static 'images/instagram-feed-img6.jpg' %}"
                                             alt="instagram-feed"></a></li>
                        <li><a href="#"><img src="{% static 'images/instagram-feed-img7.jpg' %}"
                                             alt="instagram-feed"></a></li>
                        <li><a href="#"><img src="{% static 'images/instagram-feed-img8.jpg' %}"
                                             alt="instagram-feed"></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="follow_us">
            <ul>
                <li><a target="_blank" href="#"><i class="fa fa-facebook"></i>FACEBOOK</a></li>
                <li><a id="hidden"
                       href="https://www.instagram.com/share?url=http://devbrian.com{{ request.get_full_path|urlencode }}"
                       class="instagram-link"><i class="fa fa-instagram"></i> Instagram</a>
                </li>
                <li><a target="_blank" href="#"><i class="fa fa-twitter"></i>TWITTER</a></li>
                <li><a target="_blank" href="#"><i class="fa fa-youtube"></i>YOUTUBE</a></li>
                <li><a target="_blank" href="#"><i class="fa fa-google-plus"></i>GOOGLE+</a></li>
                <li><a target="_blank" href="#"><i class="fa fa-vimeo-square"></i>VIMEO</a></li>
                <li><a target="_blank" href="#"><i class="fa fa-dribbble"></i>DRIBBBLE</a></li>
            </ul>
        </div>
        <div class="footer-1-copyright text-center">
            <p>Copyright &copy; 2016 Zedthemes.com All Rights Reserved. </p>
        </div>
    </div>
</footer>
<!-----/footer---->
<script>
    var form1 = document.getElementById('subscribeform')

    form1.addEventListener('submit', stopReload)

    function stopReload(e) {
        e.preventDefault()
        $.ajax({
            type: "POST",
            url: "{% url 'core:AddSubscriberView' %}",
            data: $("#subscribeform").serialize(),
            datatype: "json",
            success: function (data1) {

                if (data1.added == "True") {
                    alert("Subscribed to newsletter")
                } else {
                    alert("Already Subscribed to newsletter")
                }
                form1.reset()

            }
        })
    }
</script>

<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/custom.js' %}"></script>
<!-- Bootstrap Core JavaScript -->
<script src="{% static 'js/bootstrap.js' %}"></script>

</body>

</html>

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Blog Post</title>

    <!-- Bootstrap -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- custome-css -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css" media="screen">
    <!-- font awesome for icons -->
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
    <!-- google font -->
    <link href="{% static 'fonts/css8773.css?family=Merriweather:300,400,700' %}" rel='stylesheet' type='text/css'>
    <link href="{% static 'fonts/cssda6f.css?family=Open+Sans:400,600,700' %}" rel='stylesheet' type='text/css'>
   
   <style> h3 { font-family: "Brush Script MT", cursive; font-size: 26px; font-style: normal; font-variant: normal; }
    </style>
</head>
<body>

<!--navigation-->
<header class="navbar navbar-inverse">
    <div class="container">
        <div class="row">
            <div class="col-md-2">
                <div class="logo">
                    <h3>Blog Post</h3>
                </div>
            </div>

            <div class="col-md-7">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                            data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div  class="navbar-collapse collapse">
                    <ul class="nav navbar-nav text-center">
                        <li >
                            <a href="{% url 'core:HomeView' %}">Home</a>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Categories <b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href="{% url 'core:CategoryView' 'Entertainment' %}">Entertainment</a></li>
                                <li><a href="{% url 'core:CategoryView' 'Development' %}">Development</a></li>
                                <li><a href="{% url 'core:CategoryView' 'Business' %}">Business</a></li>
                                <li><a href="{% url 'core:CategoryView' 'Lifestyle' %}">Lifestyle</a></li>
                            </ul>
                        </li>
                        <li><a href="{% url 'core:ContactUsView' %}">Contact-Us</a></li>
                        <!-- <li><a href="{% url 'account_signup' %}">Write Blog for Us</a></li>
                        {% if request.user.is_authenticated %}
                            <li><a href="{% url 'account_logout' %}" style="background-color: transparent; !important;" class="active_btn">Logout</a></li>
                        {% else %}
                            <li><a href="{% url 'account_login' %}">Login</a></li>
                        {% endif %} -->
                    </ul>
                </div>
            </div>

            <div class="col-md-3">
                <div class="search">
                    <div class="search_button"><i class="fa fa-search"></i> <i class="fa fa-close"></i></div>
                    <form method="post" action="{% url 'core:SearchView' %}" role="form" id="search_form">
                        {% csrf_token %}
                        <div class="form-group has-feedback">
                            <input type="text" placeholder="Search.." name="search_form" id="id_search"
                                   class="form-control input-sm">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!--/.nav-collapse -->
</header>
<!--navigation end-->
{% block content %}


{% endblock %}
<!--popular-psots-->
<section id="popular-posts" class="padding_none">
    <div class="text-center">
        <div class="sect-heading"><p><i class="fa fa-rocket"></i>Popular Posts</p></div>
    </div>
    {% for trend in trends %}
        <div class="col-sm-4 col-md-2">
            <div class="popular_posts">
                <div class="populat_post_image">
                    <a href="{{ trend.get_absolute_url }}"> <img style="width: 100%; height: 238px"
                                                                 src="{{ trend.img.url }}" alt="image"> </a>
                </div>
                <div class="popular_posts_text">
                    <div class="populat_post_title">
                        <h5><a href="{{ trend.get_absolute_url }}">{{ trend.title }}</a></h5>
                    </div>
                    <div class="post-meta-elements">
                        <div class="meta-post-author">
                            <i class="fa fa-user"></i><a>{{ trend.author.first_name }}{{ trend.author.last_name }}</a>
                        </div>
                        <div class="meta-post-cat">
                            {% for tag in trend.tags.all %}
                                {% if forloop.counter == 1 %}
                                    <i class="fa fa-tags"></i>
                                {% endif %}
                                <a>{{ tag }}</a>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}


</section>
<!--/popular-psots-->
<!-----footer----->
<footer>
    <!-- <div class="container">
        <div class="row">
            <div class="col-md-5">
                <div class="footer_logo">
                    <a href="index-2.html"><img src="{% static 'images/logo.png' %}" alt="logo-image"></a>
                </div>
                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the
                    industry's standard dummy text ever since the 1500s, when an unknown printer took a galley.</p>
                <div class="newslatter">
                    <h4>Subscribe <em>Newsletter</em></h4>
                    <p>Get my latest adventures and updates delivered straight to your inbox. </p>
                    <div class="row">
                        <form method="post" id="subscribeform">
                            {% csrf_token %}
                            <div class="form-group">
                                <div class="col-md-7 col-sm-8">
                                    <input name="email" id="id_email" type="email" placeholder="Enter your email here"
                                           required>
                                </div>
                                <div class="col-md-5 col-sm-4">
                                    <input name="" type="submit" value="Subscribe" class="btn active_btn">
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>

            <div class="col-md-7">
                <div class="instagram-feed text-center">
                    <a href="#" class="btn instagram_btn white-btn"><i class="fa fa-instagram"></i> Join Instagram</a>
                    <ul>
                        <li><a href="#"><img src="{% static 'images/instagram-feed-img1.jpg' %}"
                                             alt="instagram-feed"></a></li>

                        <li><a href="#"><img src="{% static 'images/instagram-feed-img2.jpg' %}"
                                             alt="instagram-feed"></a></li>
                        <li><a href="#"><img src="{% static 'images/instagram-feed-img3.jpg' %}"
                                             alt="instagram-feed"></a></li>
                        <li><a href="#"><img src="{% static 'images/instagram-feed-img4.jpg' %}"
                                             alt="instagram-feed"></a></li>
                        <li><a href="#"><img src="{% static 'images/instagram-feed-img5.jpg' %}"
                                             alt="instagram-feed"></a></li>
                        <li><a href="#"><img src="{% static 'images/instagram-feed-img6.jpg' %}"
                                             alt="instagram-feed"></a></li>
                        <li><a href="#"><img src="{% static 'images/instagram-feed-img7.jpg' %}"
                                             alt="instagram-feed"></a></li>
                        <li><a href="#"><img src="{% static 'images/instagram-feed-img8.jpg' %}"
                                             alt="instagram-feed"></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div> -->
    <div class="container">
        <div class="follow_us">
            <ul>
                <li><a target="_blank" href="#"><i class="fa fa-facebook"></i>FACEBOOK</a></li>
                <li><a id="hidden"
                       href="#"
                       class="instagram-link"><i class="fa fa-instagram"></i> Instagram</a>
                </li>
                <li><a target="_blank" href="#"><i class="fa fa-twitter"></i>TWITTER</a></li>
                <li><a target="_blank" href="#"><i class="fa fa-youtube"></i>YOUTUBE</a></li>
                <li><a target="_blank" href="#"><i class="fa fa-google-plus"></i>GOOGLE+</a></li>
                
            </ul>
        </div>
    </div>
</footer>
<!-----/footer---->


<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/custom.js' %}"></script>
<!-- Bootstrap Core JavaScript -->
<script src="{% static 'js/bootstrap.js' %}"></script>

</body>

</html>